In [1]:
import numpy as np

In [2]:
inputs = np.array([[0,1,0],[1,0,1],[1,1,0],[0,0,1]])
outputs = np.array([[0],[1],[1],[0]])

In [3]:
inputs

array([[0, 1, 0],
       [1, 0, 1],
       [1, 1, 0],
       [0, 0, 1]])

In [4]:
outputs

array([[0],
       [1],
       [1],
       [0]])

In [5]:
np.random.seed(10)
weights = np.random.random((3,1))
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [6]:
sum = np.dot(inputs,weights) + 0.02
sum

array([[0.04075195],
       [1.42496888],
       [0.81207259],
       [0.65364823]])

In [7]:
### Activation Function (sigmoid)
def activation(x):
  return 1/(1+np.exp(-x))

In [8]:
### Activation Function (sigmoid)
def step_function(x):
  if x<0:
    return 0
  else:
    return 1

In [13]:
ypred = activation(sum)
ypred

array([[0.51018658],
       [0.8061162 ],
       [0.69255099],
       [0.65783211]])

In [15]:
ypred.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

In [16]:
sum = np.dot(inputs,weights) + 0.02
ypred = activation(sum)
error = outputs - ypred
error

array([[-0.51018658],
       [ 0.1938838 ],
       [ 0.30744901],
       [-0.65783211]])

In [11]:
### Create a gradient descent function
def gradient(x,e):
  return e * (x*(1-x))

In [23]:
sum = np.dot(inputs,weights) + 0.02
ypred = activation(sum)
error = outputs - ypred
chng_weight = gradient(ypred,error)   ### gradient descent
weights = weights + np.dot(inputs.T,chng_weight)
ypred

array([[0.45068529],
       [0.79353495],
       [0.72073244],
       [0.54992472]])

In [26]:
for i in range(1000):
  sum = np.dot(inputs,weights) + 0.02
  ypred = activation(sum)
  error = outputs - ypred
  chng_weight = gradient(ypred,error)   ### gradient descent
  weights = weights + np.dot(inputs.T,chng_weight)

In [27]:
error

array([[-0.02334202],
       [ 0.01642183],
       [ 0.01642183],
       [-0.02334202]])

In [28]:
ypred

array([[0.02334202],
       [0.98357817],
       [0.98357817],
       [0.02334202]])

In [29]:
ypred.round()

array([[0.],
       [1.],
       [1.],
       [0.]])

In [30]:
weights

array([[ 7.82699697],
       [-3.75414806],
       [-3.75414803]])

In [26]:
ypred = []
for i in range(4):
  sum = np.dot(inputs,weights) + 0.02
  ypred.append (step_function(sum[i][0]))

In [27]:
ypred

[1, 1, 1, 1]