In [1]:
print("We are learning Numpy")   # shift + enter

We are learning Numpy


In [2]:
!pip3 install numpy

In [3]:
import numpy as np

In [6]:
a1 = np.array([5,4,3,45,3,4,32,43,4354,5])
print(a1)

[   5    4    3   45    3    4   32   43 4354    5]


In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[5,4,3,45,3],[5,3,2,1,4],[5,4,2,42,3]])
print(a2)

[[ 5  4  3 45  3]
 [ 5  3  2  1  4]
 [ 5  4  2 42  3]]


In [9]:
a3 = np.array([[5,4,3,45,3],[5,3,2,1,4,6],[5,4,2,42,3]])
print(a3)

[list([5, 4, 3, 45, 3]) list([5, 3, 2, 1, 4, 6]) list([5, 4, 2, 42, 3])]


In [10]:
len(a2)

3

In [11]:
a2.shape

(3, 5)

In [12]:
a2 = a2.reshape(5,3)

In [13]:
a2

array([[ 5,  4,  3],
       [45,  3,  5],
       [ 3,  2,  1],
       [ 4,  5,  4],
       [ 2, 42,  3]])

In [14]:
#### Pick the elements from array (Array Slicing)

In [15]:
a2

array([[ 5,  4,  3],
       [45,  3,  5],
       [ 3,  2,  1],
       [ 4,  5,  4],
       [ 2, 42,  3]])

In [16]:
a2[2]

array([3, 2, 1])

In [17]:
a2[2:5]

array([[ 3,  2,  1],
       [ 4,  5,  4],
       [ 2, 42,  3]])

In [18]:
a2[2:]

array([[ 3,  2,  1],
       [ 4,  5,  4],
       [ 2, 42,  3]])

In [19]:
a2[:6]

array([[ 5,  4,  3],
       [45,  3,  5],
       [ 3,  2,  1],
       [ 4,  5,  4],
       [ 2, 42,  3]])

In [20]:
a2[-3]

array([3, 2, 1])

In [21]:
a2

array([[ 5,  4,  3],
       [45,  3,  5],
       [ 3,  2,  1],
       [ 4,  5,  4],
       [ 2, 42,  3]])

In [22]:
a2[3,1]

5

In [27]:
a2[1:4,1]

array([3, 2, 5])

In [28]:
a2

array([[ 5,  4,  3],
       [45,  3,  5],
       [ 3,  2,  1],
       [ 4,  5,  4],
       [ 2, 42,  3]])

In [29]:
a2.sum()

131

In [30]:
a2.sum(axis=0)    ## column wise sum

array([59, 56, 16])

In [31]:
a2.sum(axis=1)    ## row wise sum

array([12, 53,  6, 13, 47])

In [32]:
a2.mean()

8.733333333333333

In [35]:
a2[2].sum()

6

In [41]:
a2[:,2].sum()

16

In [33]:
a2

array([[ 5,  4,  3],
       [45,  3,  5],
       [ 3,  2,  1],
       [ 4,  5,  4],
       [ 2, 42,  3]])

In [42]:
a2[2]

array([3, 2, 1])

In [44]:
a2.sum(axis=0)[2] 

16

In [45]:
a2

array([[ 5,  4,  3],
       [45,  3,  5],
       [ 3,  2,  1],
       [ 4,  5,  4],
       [ 2, 42,  3]])

In [46]:
a2.max()

45

In [47]:
a2.min()

1

In [48]:
a2.argmax()

3

In [49]:
a2.argmin()

8

In [50]:
### Generate some equidistant numbers b/w a range
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [53]:
np.linspace(1,100,20,retstep=True)

(array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
         21.84210526,  27.05263158,  32.26315789,  37.47368421,
         42.68421053,  47.89473684,  53.10526316,  58.31578947,
         63.52631579,  68.73684211,  73.94736842,  79.15789474,
         84.36842105,  89.57894737,  94.78947368, 100.        ]),
 5.2105263157894735)

In [61]:
np.linspace(1,100,10,retstep=True)

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [58]:
np.arange(1,102,4.5)

array([  1. ,   5.5,  10. ,  14.5,  19. ,  23.5,  28. ,  32.5,  37. ,
        41.5,  46. ,  50.5,  55. ,  59.5,  64. ,  68.5,  73. ,  77.5,
        82. ,  86.5,  91. ,  95.5, 100. ])

In [59]:
np.linspace(1,1000,20,retstep=True)   ## retstep - display the setp value

(array([   1.        ,   53.57894737,  106.15789474,  158.73684211,
         211.31578947,  263.89473684,  316.47368421,  369.05263158,
         421.63157895,  474.21052632,  526.78947368,  579.36842105,
         631.94736842,  684.52631579,  737.10526316,  789.68421053,
         842.26315789,  894.84210526,  947.42105263, 1000.        ]),
 52.578947368421055)

In [67]:
#### Random Numbers
np.random.randint(50)   ### 0-49

30

In [72]:
np.random.seed(3)
np.random.randint(50)   ### 0-49

42

In [75]:
np.random.randint(50,500) 

181

In [76]:
np.random.randint(50,500,10) 

array([490, 306, 327, 197, 252, 413, 219, 188, 455, 169])

In [77]:
np.random.randint(50,500,(3,2)) 

array([[472, 198],
       [478, 143],
       [473, 448]])